In [1]:
!pip install nnfs

In [2]:
import numpy as np
import nnfs

nnfs.init()

## Dense Layers : fully connected layers
## Activation functions:
            - ReLU
            - Softmax

Weights defined as transpose for efficiency

In [3]:
class LayerDense:
    def __init__(self, num_inputs, num_neurons):
        # initialize weights and biases
        self.weights = 0.01 * np.random.randn(num_inputs, num_neurons) # <<- already transposed
        self.biases = np.zeros((1,num_neurons))

    def forward(self, inputs):
        # calculate output values from inputs,weights adn biases
        self.output = np.matmul(inputs, self.weights) + self.biases

In [4]:
class ActivationReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [5]:
class ActivationSoftmax:
    def forward(self, inputs):
        exp_vals = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        prob = exp_vals / np.sum(exp_vals, axis=1, keepdims=True)
        self.output = prob

In [10]:
# Example run
from nnfs.datasets import spiral_data

np.random.seed(123)
X, y = spiral_data(samples=100, classes=3)
dense1 = LayerDense(2,3)
activation1 = ActivationReLU()
dense2 = LayerDense(3,3)
activation2 = ActivationSoftmax()

dense1.forward(X)
print(dense1.output[:10])

activation1.forward(dense1.output)
print(activation1.output[:10])

dense2.forward(activation1.output)
print(dense2.output[:10])

activation2.forward(dense2.output)
print(activation2.output[:10])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 9.4573094e-05 -5.9267721e-05  7.2208582e-05]
 [ 1.6830028e-04 -8.3797575e-05  2.0559385e-04]
 [ 6.5878841e-05  6.9999973e-05  4.4613457e-04]
 [ 2.8068494e-04 -9.6152013e-05  4.9797294e-04]
 [ 4.4868878e-04 -4.2396926e-04 -1.6528208e-04]
 [ 3.9569655e-05  2.1502166e-04  8.8323408e-04]
 [ 6.3656073e-04 -3.6693056e-04  5.9982738e-04]
 [ 6.7692413e-04 -6.7931623e-04 -3.9051610e-04]
 [ 8.1240491e-04 -4.6152930e-04  7.8957796e-04]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [9.4573094e-05 0.0000000e+00 7.2208582e-05]
 [1.6830028e-04 0.0000000e+00 2.0559385e-04]
 [6.5878841e-05 6.9999973e-05 4.4613457e-04]
 [2.8068494e-04 0.0000000e+00 4.9797294e-04]
 [4.4868878e-04 0.0000000e+00 0.0000000e+00]
 [3.9569655e-05 2.1502166e-04 8.8323408e-04]
 [6.3656073e-04 0.0000000e+00 5.9982738e-04]
 [6.7692413e-04 0.0000000e+00 0.0000000e+00]
 [8.1240491e-04 0.0000000e+00 7.8957796e-04]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.39179065e-06

In [7]:
X.shape

(300, 2)

In [8]:
X[:5]

array([[0.        , 0.        ],
       [0.00299556, 0.00964661],
       [0.01288097, 0.01556285],
       [0.02997479, 0.0044481 ],
       [0.03931246, 0.00932828]], dtype=float32)