In [1]:
!pip install nnfs

In [25]:
import numpy as np
import nnfs

nnfs.init()

## Dense Layers : fully connected layers

Weights defined as transpose for efficiency

In [26]:
class LayerDense:
    def __init__(self, num_inputs, num_neurons):
        # initialize weights and biases
        self.weights = 0.01 * np.random.randn(num_inputs, num_neurons) # <<- already transposed
        self.biases = np.zeros((1,num_neurons))

    def forward(self, inputs):
        # calculate output values from inputs,weights adn biases
        self.output = np.matmul(inputs, self.weights) + self.biases

In [30]:
# Example run
X, y = nnfs.datasets.spiral_data(samples=100, classes=3)
dense1 = LayerDense(2,3)
dense1.forward(X)
print(dense1.output[:5])

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.61496280e-05 -5.70940319e-05 -1.16960771e-04]
 [-7.69893741e-05 -4.75328154e-04 -2.12466970e-04]
 [-1.19454686e-04 -6.26299181e-04 -3.77396675e-04]
 [-1.59333722e-04 -8.86327529e-04 -4.81519091e-04]]


In [31]:
X.shape

(300, 2)

In [32]:
X[:5]

array([[-0.        ,  0.        ],
       [-0.00547079,  0.00849122],
       [ 0.0105405 ,  0.01723425],
       [ 0.00670891,  0.02955104],
       [ 0.01336712,  0.03812882]], dtype=float32)